### ISSUE TITLE
What shall be the process for others to point the textbook to their DataHubs?

### ISSUE THREAD

**Issue by choldgraf** [data-8/textbook#38]
A challenge in getting non-berkeley adoption of Data 8 is merging their jupyterhub deployment with the data 8 textbook. In it's simplest form, this just means making "interact" links etc point to another jupyterhub deployment, rather than the berkeley datahub (or binder). What's the best way to accomplish this? 

Do we want non-berkeley data 8 courses to have their own textbook website? This seems like the only straightforward way for the links to point to an arbitrary jupyterhub. If so, we could either turn this repository into a cookiecutter that others can use to create gitbook files w/ custom interact links, or we could just provide a simple script users can run in order to update their links. 

What seems like a natural approach here? Most of the "clone and modify" approaches are relatively straightforward technically, but it's unclear what'll be the least-confusing to people.

**Comment by choldgraf** [comment]
cc @ryanlovett and @henchc in case they have thoughts

**Comment by ryanlovett** [comment]
The last time there was a conversation around there was the thought that various institutions could post their own textbook with custom links to {entity_name}.inferentialthinking.com. It wasn't clear how this would be managed however. Also licensing came up.

Cloning and rehosting the textbook might be challenging for some schools, but if there were no steps between bread and toast that'd be cool.

A gitbook extension would make this easier, but perhaps slightly more challenging for the end user who'd have to pick their school from a dropdown or some such. If a gitbook could accept a query string param, then a gitbook extension could dynamically alter the links without user interaction.

I made a bookmarklet that could modify the links but that is cumbersome since users need to click it on each page load. That was a quick-n-dirty hack before there were binder links in the textbook.

**Comment by choldgraf** [comment]
one thing we're playing around with in Binder is to use cookies to know which binderhub servers a user is validated against. However that requires some server-side processing so I'm not sure how possible it'd be to integrate with gitbook.

What's the technical level for the instructors we have in mind? Do they know git? GitHub? Are they comfortable with scripts?

**Comment by henchc** [comment]
a script rebuilding links and the book from a fork seems straight forward to me, I think we'll have to assume they know git and github at a basic level, and that they can execute python scripts. if not, they should be able to find someone who does.

I do like @ryanlovett suggestion though, would it be easy for other schools to just make PR's that would add them to the list?

**Comment by davidwagner** [comment]
This all seems to have been taken care of by the subsequent development work; schools can use the mechanisms found in https://berkeleydsep.gitbook.io/zero-to-data-8/deploying-data-8/set-up-your-course-website-and-textbook and https://github.com/data-8/zero-to-data-8/blob/master/misc/custom_textbook.md.
